title: Fortify Software Security Center API JavaScript sandbox
description: > # this means to ignore newlines until "baseurl:"
  A sandbox project including samples and workflows with the SSC REST API. 
  This project is intended as a tutorial to encourage learning the API and a quick way to get started.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fortify.github.io" # the base hostname & protocol for your site, e.g. http://example.com




# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

### content configuration ###
title:       "Fortify Engineering SSC Samples"
keywords:    "Fortify, security"
description: "Fortify Engineering SSC Samples"
source_link: ""
highlighter: rouge

kramdown:
  auto_ids:  false
  

